# Generated by Django 5.2.9 on 2026-01-01 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("project_id", models.CharField(max_length=50, unique=True)),
                (
                    "client_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("assign_date", models.DateField()),
                ("due_date", models.DateField()),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "team_lead",
                    models.ForeignKey(
                        limit_choices_to={"role": "team_lead"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.TextField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("revisions", models.TextField(blank=True, null=True)),
                ("time_estimated", models.FloatField(blank=True, null=True)),
                (
                    "files",
                    models.FileField(blank=True, null=True, upload_to="project_files/"),
                ),
                ("comments_qa", models.TextField(blank=True, null=True)),
                ("client_remarks", models.TextField(blank=True, null=True)),
                (
                    "assign_person",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "employee"},
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="core.project"
                    ),
                ),
            ],
        ),
    ]
