# Generated by Django 5.2.9 on 2026-01-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_project_projectdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("team_lead", "Team Lead"),
                    ("employee", "Employee"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
