# Generated by Django 5.2.9 on 2026-01-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdetail",
            name="employee_questions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
