# Generated by Django 5.2.9 on 2026-01-04 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_projectdetail_files_projectfile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projectdetail",
            old_name="comments_qa",
            new_name="comments_team_lead",
        ),
    ]
