# Generated by Django 5.2.9 on 2026-01-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_rename_comments_qa_projectdetail_comments_team_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("approval", "Approval Pending"),
                    ("revision", "Revision"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
