# Generated by Django 5.2.9 on 2026-01-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="expected_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
