# Generated by Django 5.2.9 on 2026-01-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_project_expected_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
