# Generated by Django 5.2.9 on 2026-01-15 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_project_project_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("time_estimated", models.FloatField(blank=True, null=True)),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        limit_choices_to={"role": "employee"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="core.projectdetail",
                    ),
                ),
            ],
        ),
    ]
