# Generated by Django 5.2.9 on 2026-01-15 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_projectpart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectPart",
        ),
    ]
