# Generated by Django 5.2.9 on 2026-01-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_delete_projectpart"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="qa_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="team_lead_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("approval", "Approval Pending"),
                    ("revision", "Revision"),
                    ("completed", "Completed"),
                    ("qa", "QA"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
