# Generated by Django 5.2.9 on 2026-01-18 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_project_qa_approved_project_team_lead_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="qa_person",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "qa"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qa_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="team_lead",
            field=models.ForeignKey(
                limit_choices_to={"role": "team_lead"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("team_lead", "Team Lead"),
                    ("employee", "Employee"),
                    ("qa", "QA"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
