# Generated by Django 5.2.9 on 2026-01-24 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_finalsubmissionfile"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProjectProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progress", models.PositiveIntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        limit_choices_to={"role": "employee"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_progresses",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "employee")},
            },
        ),
    ]
