# Generated by Django 5.2.9 on 2026-01-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_employeeprojectprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdetail",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
