# Generated by Django 5.2.9 on 2026-01-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_projectdetail_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectdetail",
            name="team_lead_revisions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
