# Generated by Django 5.2.9 on 2026-02-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_projectdetail_team_lead_revisions"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprojectprogress",
            name="final_submission_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeprojectprogress",
            name="working_hours",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("team_lead", "Team Lead"),
                    ("employee", "Estimator"),
                    ("qa", "QA"),
                ],
                default="employee",
                max_length=20,
            ),
        ),
    ]
