# Generated by Django 4.2.8 on 2026-02-01 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_employeeprojectprogress_final_submission_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalsubmissionfile',
            name='team_lead_uploaded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'team_lead'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamlead_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
