# Generated by Django 4.2.8 on 2026-02-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_finalsubmissionfile_team_lead_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprojectprogress',
            name='team_lead_submission_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
