# Generated by Django 4.2.8 on 2026-02-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_employeeprojectprogress_team_lead_submission_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(max_length=50),
        ),
    ]
